ci: fix multiarch apt-get install missing dep
Fixes:
Get:71 http://azure.archive.ubuntu.com/ubuntu bionic-updates/universe amd64 qemu-user-static amd64 1:2.11+dfsg-1ubuntu7.34 [9991 kB]
Get:72 http://azure.archive.ubuntu.com/ubuntu bionic/main amd64 sharutils amd64 1:4.15.2-3 [155 kB]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/w/wavpack/libwavpack1_5.1.0-2ubuntu1.4_amd64.deb  404  Not Found [IP: 52.147.219.192 80]
Fetched 80.0 MB in 2s (52.3 MB/s)
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Error: Process completed with exit code 100.

Signed-off-by: William Roberts <william.c.roberts@intel.com>