test/thread_unit.c: add missing return value for test_thread_run()
This fixes the following compiler warning/error:

test/thread_unit.c: In function ‘test_thread_run’:
test/thread_unit.c:72:1: error: no return statement in function returning non-void [-Werror=return-type]
   72 | }
      | ^

Signed-off-by: Jonas Witschel <git@diabonas.de>