test/tcti-connections-max.int: remove unused variable
Compilation with GCC 10.2.0 fails with the warning/error:

test/integration/context-util.c: In function ‘tcti_free_from_opts’:
test/integration/context-util.c:131:13: error: unused variable ‘rc’ [-Werror=unused-variable]
  131 |     TSS2_RC rc;
      |             ^~

Signed-off-by: Jonas Witschel <diabonas@gmx.de>